-- Generated by scripts/seed_from_xlsx.py. Safe to run once on an empty database.
begin;
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M01', 'Probodhini', 'Quantity Surveying & Construction', '', 'Active', false, 0);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M02', 'Saleeth Yaseen', 'Quantity Surveying & Construction', '', 'Active', true, 1);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M03', 'Sarjoon Mohd.', 'Quantity Surveying & Construction', '', 'Active', false, 2);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M04', 'Sreeba Sreejith', 'Quantity Surveying & Construction', '', 'Active', false, 3);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M05', 'Suraj Thakre', 'Quantity Surveying & Construction', '', 'Active', false, 4);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M06', 'Mohd. Hassan', 'Quantity Surveying & Construction', '', 'Active', false, 5);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M07', 'Naser Hawsah', 'Quantity Surveying & Construction', '', 'Active', false, 6);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M08', 'Varun B.P.', 'Quantity Surveying & Construction', '', 'Active', false, 7);
insert into public.members (id, name, pathway, notes, status, is_leader, sort) values ('M09', 'Ravindra Kumara', 'Quantity Surveying & Construction', '', 'Active', false, 8);
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M01', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M02', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M03', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M04', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M05', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M06', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M07', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M08', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M09', 'Contract Practice', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M01', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M02', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M03', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M04', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M05', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M06', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M07', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M08', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values ('M09', 'Procurement & Tendering', 'Technical', '', '', '', 'Not Started', '') returning id) insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M01', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M02', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M03', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M04', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M05', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M06', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M07', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M08', '', '', 'Not Started', '');
insert into public.case_studies (member_id, summary, questions, status, notes) values ('M09', '', '', 'Not Started', '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Contract Practice', 'study', '2026-09-27', 1.5, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Procurement & Tendering', 'study', '2026-09-29', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Quantification & Costing', 'study', '2026-09-30', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Commercial Management of Construction', 'study', '2026-10-04', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Project Financial Control & Reporting', 'study', '2026-10-06', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Design Economics & Cost Planning', 'study', '2026-10-07', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Construction Technology', 'study', '2026-10-11', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Case Study (Probodhini, Saleeth, Sarjoon)', 'case', '2026-10-13', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Case Study (Sreeba, Suraj, Hassan)', 'case', '2026-10-14', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Case Study (Naser, Varun, Ravindra)', 'case', '2026-10-18', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Mini mock interviews', 'mock', '2026-10-20', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Mini mock interviews', 'mock', '2026-10-21', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Mini mock interviews', 'mock', '2026-10-25', null, '');
insert into public.sessions (title, kind, session_date, hours, notes) values ('Mini mock interviews', 'mock', '2026-10-27', null, '');
insert into public.sessions (title, kind, session_date, starts_at, ends_at, notes, reminder_minutes) values ('Q&A session', 'qa', '2026-09-28', null, '2026-09-28T21:00:00+04:00', 'Runs until 9 pm UAE / Oman time. Start time to be confirmed.', 30);
insert into public.sessions (title, kind, session_date, starts_at, ends_at, hours, notes, reminder_minutes) values ('Presentation workshop', 'workshop', '2026-09-28', '2026-09-28T21:00:00+04:00', '2026-09-28T22:00:00+04:00', 1, 'Candidates who are ready present their case study presentation for a constructive discussion. At least 2 presentations are needed from each group. Attendance will be recorded.', 30);
insert into public.announcements (member_id, title, body) values ('M02', 'Presentation workshop this Monday, 9 to 10 pm', 'I am planning a workshop to go through and listen to the presentations that candidates have made.

This Monday''s Q&A session will run until 9 pm (UAE / Oman time), and from 9 to 10 pm (UAE / Oman time) we will have a workshop on presentations.

If you are ready with your presentation, please present it during the session so that a constructive discussion can be done. I may not be able to take all presentations, but at least 2 presentations from each group are required.

An attendance register will be maintained to monitor attendees and non-attendees.');
commit;
