"""Build supabase/seed.sql from the group's tracker workbook.

Usage: python3 scripts/seed_from_xlsx.py "RICS Group 03 Tracker.xlsx" > supabase/seed.sql

Only names are imported from 01-Members. Email addresses stay in the workbook
because the app has no login and anyone with the link can read what it holds.
"""

import sys
from datetime import date

import openpyxl

LEADER = "M02"  # Saleeth Yaseen
UAE_OFFSET = "+04:00"
STUDY_DAYS = {6, 1, 2}  # Sunday, Tuesday, Wednesday (Python weekday numbers)
STUDY_START, STUDY_END = "20:00", "21:30"


def q(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def text(value):
    if value is None:
        return ""
    return " ".join(str(value).split()).replace("( ", "(").replace(" )", ")")


def session_kind(title):
    lower = title.lower()
    if lower.startswith("case study"):
        return "case"
    if "mock" in lower:
        return "mock"
    return "study"


def main(path):
    wb = openpyxl.load_workbook(path, data_only=True)
    out = ["-- Generated by scripts/seed_from_xlsx.py. Safe to run once on an empty database.", "begin;"]

    members = {}
    for sort, row in enumerate(wb["01-Members"].iter_rows(min_row=4, max_col=6, values_only=True)):
        member_id, name, _contact, pathway, notes, active = row
        if not member_id or not text(name):
            continue
        members[text(name)] = member_id
        out.append(
            "insert into public.members (id, name, pathway, notes, status, is_leader, sort) values "
            f"({q(member_id)}, {q(text(name))}, {q(text(pathway) or 'Quantity Surveying & Construction')}, "
            f"{q(text(notes))}, {q('Inactive' if text(active) == 'No' else 'Active')}, "
            f"{'true' if member_id == LEADER else 'false'}, {sort});"
        )

    sheet = wb["03- SOE"]
    for row in range(5, sheet.max_row + 1, 3):
        competency = text(sheet.cell(row, 1).value)
        candidate = text(sheet.cell(row, 2).value)
        if not competency or candidate not in members:
            continue
        levels = [text(sheet.cell(row + i, 5).value) for i in range(3)]
        status = text(sheet.cell(row, 7).value) or "Not Started"
        out.append(
            "with s as (insert into public.soe (member_id, competency, competency_type, level1, level2, level3, status, notes) values "
            f"({q(members[candidate])}, {q(competency)}, {q(text(sheet.cell(row, 3).value) or 'Technical')}, "
            f"{q(levels[0])}, {q(levels[1])}, {q(levels[2])}, {q(status)}, {q(text(sheet.cell(row, 8).value))}) returning id) "
            "insert into public.qa (soe_id, number) select s.id, n from s, generate_series(1, 3) n;"
        )

    for row in wb["04- Case study"].iter_rows(min_row=5, max_col=5, values_only=True):
        candidate, shared, questions, status, notes = (text(v) for v in row)
        if candidate not in members:
            continue
        out.append(
            "insert into public.case_studies (member_id, summary, questions, status, notes) values "
            f"({q(members[candidate])}, {q(shared)}, {q('' if questions == 'Other candidate questions' else questions)}, "
            f"{q(status or 'Not Started')}, {q(notes)});"
        )

    # Study sessions run on Sunday, Tuesday and Wednesday, 8:00 to 9:30 pm UAE / Oman time.
    # Study days in the plan without a topic yet get a placeholder session.
    for row in wb["02- Calander"].iter_rows(min_row=4, max_col=5, values_only=True):
        day, _weekday, topic, hours, notes = row
        if not day:
            continue
        timed = day.weekday() in STUDY_DAYS
        if not text(topic) and not timed:
            continue
        title = text(topic) or "Study session (topic TBC)"
        iso = day.date().isoformat()
        starts = q(f"{iso}T{STUDY_START}:00{UAE_OFFSET}") if timed else "null"
        ends = q(f"{iso}T{STUDY_END}:00{UAE_OFFSET}") if timed else "null"
        planned = 1.5 if timed else (None if hours in (None, "") else float(hours))
        out.append(
            "insert into public.sessions (title, kind, session_date, starts_at, ends_at, hours, notes) values "
            f"({q(title)}, {q(session_kind(title))}, {q(iso)}, {starts}, {ends}, "
            f"{'null' if planned is None else planned}, {q(text(notes))});"
        )

    # From the organiser's WhatsApp message: this Monday's Q&A runs until 9 pm and the
    # presentation workshop follows from 9 to 10 pm, UAE / Oman time.
    monday = date(2026, 9, 28).isoformat()
    out.append(
        "insert into public.sessions (title, kind, session_date, starts_at, ends_at, notes, reminder_minutes) values "
        f"('Q&A session', 'qa', {q(monday)}, null, {q(monday + 'T21:00:00' + UAE_OFFSET)}, "
        "'Runs until 9 pm UAE / Oman time. Start time to be confirmed.', 30);"
    )
    out.append(
        "insert into public.sessions (title, kind, session_date, starts_at, ends_at, hours, notes, reminder_minutes) values "
        f"('Presentation workshop', 'workshop', {q(monday)}, {q(monday + 'T21:00:00' + UAE_OFFSET)}, "
        f"{q(monday + 'T22:00:00' + UAE_OFFSET)}, 1, "
        "'Candidates who are ready present their case study presentation for a constructive discussion. "
        "At least 2 presentations are needed from each group. Attendance will be recorded.', 30);"
    )

    announcement = (
        "I am planning a workshop to go through and listen to the presentations that candidates have made.\n\n"
        "This Monday's Q&A session will run until 9 pm (UAE / Oman time), and from 9 to 10 pm (UAE / Oman time) "
        "we will have a workshop on presentations.\n\n"
        "If you are ready with your presentation, please present it during the session so that a constructive "
        "discussion can be done. I may not be able to take all presentations, but at least 2 presentations from "
        "each group are required.\n\n"
        "An attendance register will be maintained to monitor attendees and non-attendees."
    )
    out.append(
        "insert into public.announcements (member_id, title, body) values "
        f"({q(LEADER)}, 'Presentation workshop this Monday, 9 to 10 pm', {q(announcement)});"
    )

    out.append("commit;")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
